#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js: stable
sudo: false

cache:
  apt: true
  directories:
    - node_modules

#安装的脚本命令
install:
  - npm install
  - cd ./test/smoke/template
  - npm install
  - cd ../../../

#运行的脚本命令
script:
  - npm test

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master